import streamlit as st
import numpy as np
import re
import pickle
import json
from keras.preprocessing.sequence import pad_sequences
from keras.models import load_model

st.set_page_config(
    page_title="Human written vs AI Generated Text Detector",
    page_icon="🤖",
    layout="centered"
)

st.markdown("""
<style>

/* Remove Streamlit top space */
header[data-testid="stHeader"]{
    background:transparent;
}

.stApp{
    background:#151313;
    color:#f5f5f4;
}

.block-container{
    max-width:850px;
    padding-top:2.5rem;
    padding-bottom:3rem;
}

/* Title */
h1{
    text-align:center;
    color:#fafaf9;
    font-size:40px;
    font-weight:700;
    margin-bottom:20px;
}

/* Caption */
.stCaption{
    color:#a8a29e !important;
    font-size:15px;
    margin-bottom:22px;
}

/* Image */
[data-testid="stImage"] img{
    width:100%;
    height:350px;
    object-fit:cover;
    border-radius:14px;
    margin-bottom:12px;
}

/* Textarea outer box */
div[data-baseweb="textarea"]{
    background:#211f1f !important;
    border:1px solid #44403c !important;
    border-radius:12px !important;
    box-shadow:none !important;
}

/* Remove blue focus */
div[data-baseweb="textarea"]:focus-within{
    border:1px solid #78716c !important;
    box-shadow:none !important;
    outline:none !important;
}

/* Actual textarea */
textarea,
textarea:focus,
textarea:focus-visible{
    background:#211f1f !important;
    color:#fafaf9 !important;
    border:none !important;
    outline:none !important;
    box-shadow:none !important;
    font-size:16px !important;
    padding:16px !important;
}

/* Button */
.stButton{
    display:flex;
    justify-content:center;
    margin-top:10px;
}

.stButton > button{
    width:850px;
    height:50px;
    background:#c2410c;
    color:white;
    border:none;
    border-radius:10px;
    font-size:17px;
    font-weight:600;
}

.stButton > button:hover{
    background:#9a3412;
    color:white;
    border:none;
}

/* Result cards */
[data-testid="column"]{
    background:#211f1f;
    border:1px solid #44403c;
    border-radius:12px;
    padding:18px;
}

/* Headers */
h2, h3{
    color:white;
}

/* Success */
.stSuccess{
    border-radius:12px;
}

/* Warning */
.stWarning{
    border-radius:12px;
}

/* Spinner */
.stSpinner{
    color:white;
}

</style>
""", unsafe_allow_html=True)

model = load_model("ai_generated_text_detector.keras")

with open("text_tokenizer.pkl", "rb") as file:
    tokenizer = pickle.load(file)
with open("stop_words.pkl", "rb") as file:
    stop_words = pickle.load(file)
with open("configuration.json", "r") as file:
    configuration = json.load(file)

MAX_LEN = configuration["MAX_LEN"]
THRESHOLD = configuration["threshold"]

st.title("Human-Written vs AI-Generated Text Detection Using BiLSTM and Word2Vec")

st.image('https://www.yomu.ai/images/blog-images/ai-essay-reviewers/ai-vs-human-writer.webp',width=800)

st.caption("Enter a complete paragraph or article to detect whether it was " "written by a human or generated by artificial intelligence.")

user_input = st.text_area("Text Content",height=220,placeholder="Paste the complete text here...")

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]"," ",text)
    text = re.sub( r"\s+"," ",text).strip()
    words = text.split()
    tokens = [word for word in words if word not in stop_words]
    return tokens

if st.button("Analyze Text"):
    if not user_input.strip():
        st.warning("Please enter some text for analysis.")
    else:
        tokens = preprocess(user_input)
        if len(tokens) < 10:
            st.warning(f"Only {len(tokens)} useful words remained after preprocessing. " 
                       "Please enter a longer paragraph for a more reliable prediction.")
        else:
            sequence = tokenizer.texts_to_sequences([tokens])
            padded_sequence = pad_sequences(sequence,maxlen=MAX_LEN,padding="pre",truncating="post")
            with st.spinner("Analyzing writing patterns..."):
                ai_probability = float(model.predict(padded_sequence,verbose=0)[0][0])
            human_probability = 1 - ai_probability
            if ai_probability >= THRESHOLD:
                label = "AI Generated"
                confidence = ai_probability
            else:
                label = "Human Written"
                confidence = human_probability
            st.divider()
            st.subheader("Prediction Results")
            col1, col2 = st.columns(2)
            with col1:
                st.metric("Prediction",label)
            with col2:
                st.metric("Confidence",f"{confidence:.2%}")
            st.caption(f"AI Generated Probability: {ai_probability:.2%}")
            st.caption(f"Human Written Probability: {human_probability:.2%}")
            st.progress(min(max(float(confidence), 0.0),1.0))

            if label == "AI Generated":
                st.warning("The submitted text contains patterns similar to " "AI-generated writing.")
            else:
                st.success("The submitted text contains patterns similar to " "human-written content.")